---
development:
  cloud_name: stuff
  api_key: '668358452626679'
  api_secret: BK-PLbnOp4JcZg03MJGaupjImJE
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: stuff
  api_key: '668358452626679'
  api_secret: BK-PLbnOp4JcZg03MJGaupjImJE
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: stuff
  api_key: '668358452626679'
  api_secret: BK-PLbnOp4JcZg03MJGaupjImJE
  enhance_image_tag: true
  static_image_support: false
