# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d347739a09c2e2de23d0481bf2eb841a0df514a53677bd51044b8ab65f403fe731a995964a93363e56096d8eddffa0d7a4f18ffc324b0eae328fcb9b3fb0bf5c

test:
  secret_key_base: 7824192e2640acf5611c89130469916e659e71297e309414adbf6d3b9221f8252ac86eccac976c877fd93b52a9d862b3ceed95e3ad686fc10a307e5c263a5fb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
